-- MySQL Script generated by MySQL Workbench
-- Вс 02 дек 2018 00:27:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema washington_posts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema washington_posts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `washington_posts` DEFAULT CHARACTER SET utf8 ;
USE `washington_posts` ;

-- -----------------------------------------------------
-- Table `washington_posts`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `washington_posts`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `body` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `washington_posts`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `washington_posts`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `body` VARCHAR(255) NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comment_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `washington_posts`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `washington_posts`.`post`
-- -----------------------------------------------------
START TRANSACTION;
USE `washington_posts`;
INSERT INTO `washington_posts`.`post` (`id`, `name`, `body`) VALUES (1, 'Фантастический выигрыш в лотерею', NULL);
INSERT INTO `washington_posts`.`post` (`id`, `name`, `body`) VALUES (2, 'Матч нашей футборльной команды', NULL);
INSERT INTO `washington_posts`.`post` (`id`, `name`, `body`) VALUES (3, 'На какой фильм сходить в субботу?', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `washington_posts`.`comment`
-- -----------------------------------------------------
START TRANSACTION;
USE `washington_posts`;
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (1, 3, 'Думаю на \'Фантастические твари\'', 'Алексей');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (2, 1, 'я как то 100 руб выиграл', 'Иван');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (3, 1, 'тоже так хочу', 'Андрей');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (4, 2, 'Наши молодцы!', 'Алексей');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (5, 3, 'лучше терминатора 2 нету', 'Дмитрий');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (6, 3, 'мультики люблю', 'Игорь');
INSERT INTO `washington_posts`.`comment` (`id`, `post_id`, `body`, `author`) VALUES (7, 1, 'Форсаж IX !!!', 'Вадим');

COMMIT;

