-- MySQL Script generated by MySQL Workbench
-- Чт 22 ноя 2018 15:28:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profession` (
  `prof_id` INT NOT NULL AUTO_INCREMENT,
  `profession` VARCHAR(45) NULL,
  PRIMARY KEY (`prof_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zip_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zip_code` (
  `zip_code` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`zip_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`my_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`my_contacts` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `prof_id` INT NULL,
  `zip_code` INT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_my_contacts_profession_idx` (`prof_id` ASC),
  INDEX `fk_my_contacts_zip_code1_idx` (`zip_code` ASC),
  CONSTRAINT `fk_my_contacts_profession`
    FOREIGN KEY (`prof_id`)
    REFERENCES `mydb`.`profession` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_my_contacts_zip_code1`
    FOREIGN KEY (`zip_code`)
    REFERENCES `mydb`.`zip_code` (`zip_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interests` (
  `interest_id` INT NOT NULL AUTO_INCREMENT,
  `interest` VARCHAR(45) NULL,
  PRIMARY KEY (`interest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_interest` (
  `interest_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`interest_id`, `contact_id`),
  INDEX `fk_contact_interest_my_contacts1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_contact_interest_interests1`
    FOREIGN KEY (`interest_id`)
    REFERENCES `mydb`.`interests` (`interest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_interest_my_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`my_contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seeking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seeking` (
  `seeking_id` INT NOT NULL,
  `seeking` VARCHAR(45) NULL,
  PRIMARY KEY (`seeking_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_seeking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_seeking` (
  `contact_id` INT NOT NULL,
  `seeking_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`, `seeking_id`),
  INDEX `fk_contact_seeking_seeking1_idx` (`seeking_id` ASC),
  CONSTRAINT `fk_contact_seeking_my_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`my_contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_seeking_seeking1`
    FOREIGN KEY (`seeking_id`)
    REFERENCES `mydb`.`seeking` (`seeking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_current`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_current` (
  `contact_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `salary` INT NULL,
  `start_date` DATE NULL,
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `fk_job_current_my_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`my_contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_desired`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_desired` (
  `contact_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `salary_low` INT NULL,
  `salary_high` INT NULL,
  `avalible` VARCHAR(45) NULL,
  `years_exe` VARCHAR(45) NULL,
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `fk_job_desired_my_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`my_contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_listings` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `salary` INT NULL,
  `zip` VARCHAR(45) NULL,
  `description` BLOB NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
